### ISSUE TITLE
Research requests not rendering at https://openai.com/requests-for-research/

### ISSUE THREAD

**Issue by jroes** [openai/requests-for-research#25]
Hey there,

No content seems to be rendering on the right-hand side of the page at https://openai.com/requests-for-research/ in either Chrome or Safari on OS X.

I cloned things down locally, ran `make`, and content seemed to render, so I'm imagining this is something on the server operations side.

**Comment by nottombrown** [comment]
Whoops, pushed up a fix https://openai.com/requests-for-research/. Thanks for the notification!
