### ISSUE TITLE
openai.com/requests-for-research/ is broken

### ISSUE THREAD

**Issue by guotong1988** [openai/requests-for-research#44]
<img width="295" alt="image" src="https://github.com/openai/requests-for-research/assets/4702353/b7ec6b20-83f6-457c-ad48-0cb8b26306cb">

**Comment by hammad93** [comment]
It mentions on the README,
```
Status: Archive (code is provided as-is, no updates expected)
```
If we navigate to the _requests_for_research directory, we can see the items that used to exist. However, it looks like the last update is 7 to 8 years ago (before the release of ChatGPT) and most of them are deprecated or solved in some way.

For example,
https://github.com/openai/requests-for-research/blob/master/_requests_for_research/im2latex.html
We're able to do this already by giving ChatGPT an image and it will respond with the LaTeX interpretation.
